** 第四章 cpu 的组成
** 
** 概述
*** cpu 的构造法
对于一个 cpu , 其中分为三个部分. 第一个部分是处理器, 第二部分是内存,
第三部分是总线. 

处理器, 里面由 ALU, 寄存器, PC

内存, 就是内存相关的, Cache 缓存, memory 内存. 

总线, 就是 IO 相关的
*** PC
PC 就是存储着指令, 其告诉 ALU 该如何处理寄存器. 

*** ALU
ALU 就是运算单元, 其能够执行 add sub 等指令, 对寄存器进行操作. 
*** CACHE
**** Cache 简介
Cache 是缓存, 是一种更为快速的内存

对于这个存储单元的层级, 我们可以回想一下, 寄存器是稀少而快速, 内存是数
量多而没那么快速, 缓存应该是介于这两者之间. 价格也是介于两者之间. 

Cache 的构想应该和 register 的构想很类似, 内存之中数据暂存在 cache 之
中, 以此达成加速的目的. 
**** SRAM
Cache memory operates between 10 to 100 times faster than RAM,
requiring only a few nanoseconds to respond to a CPU request. The name
of the actual hardware that is used for cache memory is high-speed
static random access memory (SRAM).

实现的 Cache 的硬件为 SRAM, 全称为 high-speed static random access 
memory. 于 SRAM 对应的便是 DRAM 后者用于 memory 的构造之中. S for
static , SRAM 之中的数据, 只要 power 没有断开, 不同于 DRAM 的数据那样,
就能够已知保存, 但是 DRAM 之中的数据, 几秒钟后就会消失, 需要周期性地
refresh 一下. 这就是为什么其称为 static 的. SRAM use latches and transistor to store data. 
**** Cache 的多级建构
Cache 的构造实际上更为复杂, Cache 分为了三个 Level, L3 速度最慢, 是用
来辅助 L1, L2 的. 

Cache memory is a small amount of fast memory that is used to store frequently accessed data. It is located close to the CPU and is used to reduce the average time it takes to access data from the main memory.

There are three general levels of cache: L1 cache, L2 cache, and L3 cache. Each level is differentiated by its speed, size, and proximity to the CPU.

L1 cache, or primary cache, is extremely fast but relatively small. It is usually embedded in the processor chip as CPU cache³.

L2 cache, or secondary cache, is often more capacious than L1 but slower. It is usually located on the processor chip or on a separate chip on the motherboard³.

L3 cache, or tertiary cache, is larger than L2 but slower. It is usually located on a separate chip on the motherboard³.

Is there anything else you would like to know about cache memory?

Computers, Explained -SearchStorage. https://www.techtarget.com/searchstorage/definition/cache-memory
访问时间 2023/4/1.

(2) Explainer: L1 vs. L2 vs. L3 Cache |
TechSpot. https://www.techspot.com/article/2066-cpu-l1-l2-l3-cache/ 访
问时间 2023/4/1.

(3) How Does CPU Cache Work and What Are L1, L2, and L3 Cache? -
MUO. https://www.makeuseof.com/tag/what-is-cpu-cache/ 访问时间
2023/4/1.                                               

*** Memory
**** 