22:
	xelatex --shell-escape 22.ega
23:
	xelatex --shell-escape 23.mst
24: 
	xelatex --shell-escape 24.sssp
25:
	xelatex --shell-escape 25.apsp
26: 
	xelatex --shell-escape 26.mf
27: 
	xelatex --shell-escape 27.gm

